# Generated by Django 5.1.3 on 2024-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='raw_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
