# Generated by Django 5.1.3 on 2024-11-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taglist_fileanalysis_keywords_and_more'),
        ('core', '0005_alter_fileanalysis_keywords_alter_taglist_tags'),
    ]

    operations = [
    ]
